# Generated by Django 6.0.3 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_result_tab_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_per_attempt',
            field=models.IntegerField(default=0, help_text='0 = выдавать все вопросы'),
        ),
    ]
